<h1 style = "font-size:3rem;color:orange">100 Numpy Exercises</h1>

1. Import the numpym package under the name 'np'.

In [2]:
import numpy as np

2. Print the numpy version and the configuration.

In [5]:
print(np.__version__)

1.26.2


3. Create a null vector of size 10.

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array.

In [4]:
Z = np.zeros((10, 10))
print("{} bytes".format(Z.size * Z.itemsize))

800 bytes


5. How to get the documentation of the numpy add function from the command line?

In [8]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1.

In [22]:
print(np.hstack((np.ones(5), np.zeros(5))))

Z = np.zeros(10)
Z[:5] = 1
print(Z)

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49.

In [24]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last).

In [32]:
vector = np.arange(11)
print(vector)

print(vector[::-1])
print(np.flip(vector))

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]
[10  9  8  7  6  5  4  3  2  1  0]


9. Create a 3x3 matrix with values ranging from 0 to 8.

In [33]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [40]:
vector = np.array([1, 2, 0, 0, 4, 0])

print(vector.nonzero())

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix.

In [41]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 matrix with random values.

In [76]:
print(np.random.randint(9, size=(3, 3, 3)))

print(np.random.random((3, 3, 3)))

[[[5 0 0]
  [1 6 5]
  [8 7 3]]

 [[7 0 0]
  [5 5 4]
  [0 2 3]]

 [[7 1 0]
  [8 3 8]
  [1 3 1]]]
[[[0.45573295 0.91382609 0.08795777]
  [0.14090465 0.84195269 0.74687538]
  [0.41457062 0.36472322 0.12398738]]

 [[0.02248665 0.64443981 0.99453765]
  [0.41704502 0.28751841 0.53563402]
  [0.83886982 0.93505748 0.80524754]]

 [[0.4622325  0.10139794 0.7385701 ]
  [0.18229832 0.21641264 0.17158432]
  [0.85157657 0.39555179 0.2907252 ]]]


13. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
array = np.random.randint(100, size=(10, 10))
print(array)

print(array.min())
print(array.max())
print(np.amin(array))
print(np.amax(array))

[[56 66 51 60 36 18 27 43 59 94]
 [77 99 77 31  5  2 80 85 15 62]
 [ 8 66 30 96 74 14 42 41 94 49]
 [36  5 28 82 45  9 21 83  9 84]
 [47 57 97 79 38 25 95 47 49  5]
 [35 14 53 28 22 59 18 93  0 54]
 [50 60 88 54 74 89 30 13 84 21]
 [83 82 16 86 23 50  3 39 30 58]
 [ 2 12 36 74 25 12 48 13 57 84]
 [19 57 86 15 94 91 69  1 97 66]]
0
99
0
99


14. Create a random vector of size 30 and find the mean value.

In [74]:
array = np.random.randint(100, size=30)
print(array)

print(array.mean())

[60  7 75 75  6 93 14 30 74 78 61 14 62 47 86 61 47 38 59 20 35 48 43 74
  5 60 32 87 74 17]
49.4


15. Create a 2D array with 1 on the border and 0 inside.

In [81]:
array = np.ones((10, 10))
print(array)

array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [86]:
array = np.ones((10, 10))
print(array)

print(np.pad(array, pad_width=1, mode='constant', constant_values=0))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [8]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal.

In [13]:
array = np.diag(1+np.arange(4), k=-1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
